sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /

sonata_media_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /gallery    