parameters:
  stiwl_page.admin.news_language.class: Stiwl\PageBundle\Admin\NewsLanguageAdmin
  stiwl_page.admin.news.class: Stiwl\PageBundle\Admin\NewsAdmin
  
  
services:
  stiwl_page.admin.news:
    class: %stiwl_page.admin.news.class%
    tags:
        - { name: sonata.admin, manager_type: orm , group: page, label: news }
    arguments: [null, Stiwl\PageBundle\Entity\News, StiwlPageBundle:Admin/NewsAdmin ]
    
  stiwl_page.admin.news_language:
    class: %stiwl_page.admin.news_language.class%
    tags:
        - { name: sonata.admin, manager_type: orm , group: page, label: news_languages }
    arguments: [null, Stiwl\PageBundle\Entity\NewsLanguage, SonataAdminBundle:CRUD ]