sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /
#    requirements:
#        _locale: es|en|fr
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /